### ISSUE TITLE
measurement interval unclear

### ISSUE THREAD

**Issue by wspeth** [Gio-dot/Z1-Mini#2]
sorry to bother but from the published material I cannot figure out at which frequency the values are measured and transmitted.

From https://ptvo.info/zigbee-configurable-firmware-features/premium/ it appeares some LED is blinking at either 5 seconds intervals or at 30 seconds intervals but I doubt this is the same for measurement.

can you shed some light into the behaviour please?

**Comment by gio-dot** [comment]
Hi, here is the place where you can set reporting interval:
![Screenshot_20210912-030238_Chrome](https://user-images.githubusercontent.com/55327160/132967318-d2511999-0ba6-4233-a53e-4c5bfdb2c926.jpg)

**Comment by wspeth** [comment]
oh, got it
so it is one second to 65536 seconds (>18h). Great.
Thanks a lot
will go to Italy in a week (Giglio) and have an espresso celebrating your
work ;-)


Walter

Am So., 12. Sept. 2021 um 03:05 Uhr schrieb Giovanni <
***@***.***>:

**Comment by gio-dot** [comment]
Cheers. You are welcome ;)
