### ISSUE TITLE
Board Schematic?

### ISSUE THREAD

**Issue by clomads** [Gio-dot/Z1-Mini#3]
I don't see a license, but assuming you're selling on Tinde I'd expect some sort of open source license. Do you plan on releasing your board schematics or gerbers? I'd love to show monetary support, but nearly $40 to the US doesn't make sense when I can get 10 of the modules for $26 on AliExpress. I'm mostly interested in what you're using to allow the board voltage to be up to 13.2v, but any support components would be helpful to make my own boards.

**Comment by Nailik** [comment]
Same for me, i would like to integrate an ultrasonic sensor to be used as hand wave zigbee sensor.
